app = 'minha-receita-api'
primary_region = 'ams'

[build]
  image = 'ghcr.io/cuducos/minha-receita:main'

[env]
  PORT = '8888'
  NEW_RELIC_LOG = 'stdout'

[http_service]
  internal_port = 8888
  force_https = true
  auto_stop_machines = 'suspend'
  auto_start_machines = true
  min_machines_running = 1
  max_machines_running = 2
  processes = ['app']

[[http_service.checks]]
  grace_period = "30s"
  interval = "1m"
  method = "GET"
  timeout = "3s"
  path = "/healthz"

[[vm]]
  size = 'shared-cpu-2x'
