app = 'minha-receita-mirror'
primary_region = 'ams'

[build]
  image = 'ghcr.io/cuducos/minha-receita:main'

[experimental]
  cmd = ["mirror"]

[env]
  AWS_DEFAULT_REGION = 'us-east-1'
  BUCKET = 'minhareceita'
  ENDPOINT_URL = 'https://nyc3.digitaloceanspaces.com'
  PORT = '8888'
  PUBLIC_DOMAIN = 'https://bucket.minhareceita.org/'

[http_service]
  internal_port = 8888
  force_https = true
  auto_stop_machines = 'suspend'
  auto_start_machines = true
  min_machines_running = 1
  max_machines_running = 1
  processes = ['app']

[[http_service.checks]]
  grace_period = "30s"
  interval = "1m"
  method = "GET"
  timeout = "3s"
  path = "/healthz"

[[vm]]
  size = 'shared-cpu-1x'
