name: Format
on: [push, pull_request]
jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: "1.22"
      - run: if [ "$(gofmt -s -l . | wc -l)" -gt 0 ]; then exit 1; fi
