name: Lint
on: [push, pull_request]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: "1.22.x"
      - run: "go install honnef.co/go/tools/cmd/staticcheck@v0.5.1"
      - run: "staticcheck ./..."
