name: Lint
on: [push, pull_request]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: "1.21.x"
      - run: "go install honnef.co/go/tools/cmd/staticcheck@2023.1.6"
      - run: "staticcheck ./..."
